# Make file for Module 1 Task 0

TOP_DIR = $(realpath ../../ee477-hammer-cad)
OBJ_DIR = build
INPUT_CFGS =cfg/clk_gen_ds_cfg.yml cfg/clk_gen_ds_src.yml
TB_CFGS = cfg/clk_gen_ds_tb.yml

include $(TOP_DIR)/module_top.mk
